apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app: node-exporter-pod
  name: node-exporter-pod
spec:
  selector:
    matchLabels:
      app: node-exporter-pod
  template:
    metadata:
      labels:
        app: node-exporter-pod
    spec:
      containers:
        - image: prom/node-exporter
          name: node-exporter
          ports:
            - containerPort: 9100
