apiVersion: v1
kind: Service
metadata:
  name: node-exporter-svc
  labels:
    app: node-exporter-svc
spec:
  type: NodePort
  selector:
    app: node-exporter-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9100
