apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry-pod
  name: registry-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-pod
  template:
    metadata:
      labels:
        app: registry-pod
    spec:
      containers:
        - image: registry:2
          name: registry
          ports:
          - containerPort: 5000
