apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  labels:
    app: registry-svc
spec:
  type: NodePort
  selector:
    app: registry-pod
  ports:
    - protocol: TCP
      nodePort: 31320
      port: 5000
      targetPort: 5000
