apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grafana-pod
  name: grafana-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana-pod
    spec:
      volumes:
        - name: grafana-config-volume
          configMap:
            name: grafana-config
        - name: grafana-persistent-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
      containers:
        - image: grafana/grafana
          name: grafana
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-config-volume
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
              subPath: grafana.json
            - name: grafana-persistent-volume
              mountPath: /var/lib/grafana
