apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chespirito-pod
  name: chespirito-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chespirito-pod
  template:
    metadata:
      labels:
        app: chespirito-pod
    spec:
      containers:
        - image: colima:31320/chespirito
          imagePullPolicy: Always
          name: app
          ports:
          - containerPort: 3000
