apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-pod
  name: prometheus-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-pod
    spec:
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
      containers:
      - image: prom/prometheus
        name: prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: prometheus-config-volume
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
