apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: pr-trigger
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "eventTypes"
              value: ["pull_request"]
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-pr-template
    - name: push-trigger
      interceptors:
        - ref:
            name: "github"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "eventTypes"
              value: ["push"]
            - name: "filter"
              value: "body.ref == 'refs/heads/main'"
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-pr-template
