apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pr
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: pr-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "eventTypes"
              value: ["pull_request"]
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-pr-template
    - name: push-main-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "header['X-Github-Event'] == 'push' && body.ref == 'refs/heads/main'"
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-pr-template
