apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-el
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: pr-trigger
      interceptors:
        - ref:
            name: "cel"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "filter"
              value: >
                header.match('x-github-event', 'pull_request') && body.action in ['opened', 'synchronize']
      bindings:
        - ref: github-ci-binding
      template:
        ref: github-ci-template
    - name: push-main-trigger
      interceptors:
        - ref:
            name: "cel"
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: "filter"
              value: >
                header.match('x-github-event', 'push') && body.ref == 'refs/heads/main'
      bindings:
        - ref: github-ci-binding
      template:
        ref: github-ci-template
